FROM balenalib/%%BALENA_ARCH%%-debian:buster

WORKDIR /usr/src/app

# Install python 3 and balena SDK dependencies.
RUN install_packages build-essential python3 python3-pip python3-setuptools \
    python3-dev libffi-dev libssl-dev nano

# Install balena python SDK in python 3.
RUN pip3 install RPi.GPIO paho-mqtt


COPY *.py ./


CMD ["python3", "server.py"]
